# To collect build duration & memory usage, we trigger two builds
# So we get cold and warm build timings. This is for the cold build.
name: Code updates
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "x-gatsby-cache: false" -H "x-runner-type: PREVIEW" -X POST -d {} https://webhook.gatsbyjs.com/hooks/builds/trigger/ef72ee3e-d870-4196-ae42-e8e1c5ec8fcd
